version: '3.5'

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

services:
  agency:
    image: ${AGENCY_IMAGE:-vcxagency:latest}
    container_name: agency
    logging: *service-logging
    environment:
      - LOG_JSON_TO_CONSOLE=false
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - SERVER_MAX_REQUEST_SIZE_KB=300

      - PG_WALLET_MAX_CONNECTIONS=90
      - PG_WALLET_CONNECTION_TIMEOUT_MINS=30

      - AGENCY_WALLET_NAME=vcxagency-node-ea
      - AGENCY_DID=VsKV7grR1BUE29mG2Fm2kX
      - AGENCY_SEED_SECRET=0000000000000000000000000Forward
      - AGENCY_WALLET_KEY_SECRET=98765432109876543210

      - AGENCY_TYPE=client
      - REDIS_URL=redis://redis.absadocker:6379/0

      - MYSQL_HOST=mysql.absadocker
      - MYSQL_PORT=3306
      - MYSQL_ACCOUNT=root
      - MYSQL_PASSWORD_SECRET=mysecretpassword
      - MYSQL_DATABASE_APPLICATION=agency_application
      - MYSQL_DATABASE_WALLET=agency_wallets
      - MYSQL_DATABASE_WALLET_CONNECTION_LIMIT=50

      - SERVER_ENABLE_TLS=false
    networks:
      - absadocker
    ports:
      - "8080:8080"
    command: ["sh", "-c", "env && echo \"Starting docker; MYSQL_HOST=$$MYSQL_HOST\" && npm run dev:schema:migrate:all && npm run serve"]
