version: '3.5'

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

services:
  agency:
    image: ${AGENCY_IMAGE:-vcxagency:latest}
    container_name: agency
    logging: *service-logging
    depends_on:
      - postgres
      - mysql
    environment:
      - LOG_JSON_TO_CONSOLE=false
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - SERVER_MAX_REQUEST_SIZE_KB=300

      - PG_WALLET_MAX_CONNECTIONS=90
      - PG_WALLET_CONNECTION_TIMEOUT_MINS=30

      - AGENCY_WALLET_NAME=vcxagency-node-ea
      - AGENCY_DID=VsKV7grR1BUE29mG2Fm2kX
      - AGENCY_SEED_SECRET=0000000000000000000000000Forward
      - AGENCY_WALLET_KEY_SECRET=98765432109876543210

      - AGENCY_TYPE=enterprise
      - WALLET_TYPE=mysql

      - MYSQL_WALLET_HOST=mysql.absadocker
      - MYSQL_WALLET_PORT=3306
      - MYSQL_WALLET_ACCOUNT=root
      - MYSQL_WALLET_PASSWORD_SECRET=mysecretpassword
      - MYSQL_WALLET_DB_NAME=agency-ea

      - PG_STORE_HOST=postgres.absadocker
      - PG_STORE_PORT=5432
      - PG_STORE_ACCOUNT=postgres
      - PG_STORE_PASSWORD_SECRET=mysecretpassword
      - PG_STORE_DATABASE=storage-ea

      - SERVER_ENABLE_TLS=false
    networks:
      - absadocker
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sleep 5 && npm run serve"]
