version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    networks:
      - absadocker
    ports:
      - "5432:5432"
    command: [ "-c", "config_file=/etc/postgresql.conf" ]

