version: '3.5'

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

services:
  agency:
    image: ${AGENCY_IMAGE:-vcxagency:latest}
    container_name: agency
    logging: *service-logging
    depends_on:
      - postgres
      - redis
    environment:
      - LOG_JSON_TO_CONSOLE=false
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - SERVER_MAX_REQUEST_SIZE_KB=300

      - PG_WALLET_MAX_CONNECTIONS=90
      - PG_WALLET_CONNECTION_TIMEOUT_MINS=30

      - AGENCY_WALLET_NAME=vcxagency-node-ca
      - AGENCY_DID=VsKV7grR1BUE29mG2Fm2kX
      - AGENCY_SEED_SECRET=0000000000000000000000000Forward
      - AGENCY_WALLET_KEY_SECRET=98765432109876543210

      - AGENCY_TYPE=client
      - REDIS_URL=redis://redis.absadocker:6379/0

      - PG_STORE_HOST=postgres.absadocker
      - PG_STORE_PORT=5432
      - PG_STORE_ACCOUNT=postgres
      - PG_STORE_PASSWORD_SECRET=mysecretpassword
      - PG_STORE_DATABASE=storage-ea

      - PG_WALLET_ACCOUNT=postgres
      - PG_WALLET_PASSWORD_SECRET=mysecretpassword
      - PG_WALLET_ADMIN_ACCOUNT=postgres
      - PG_WALLET_ADMIN_PASSWORD_SECRET=mysecretpassword
      - PG_WALLET_URL=postgres.absadocker:5432

      - SERVER_ENABLE_TLS=false
    networks:
      - absadocker
    ports:
      - "8080:8080"
