version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:6.0.8
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - absadocker
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
