version: '3.5'

services:
  redis:
    container_name: redis
    image: ${REDIS_IMAGE:-redis:cached}
    networks:
      - absadocker
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
